# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

version: "0.2"
language: en

ignorePaths:
  - "node_modules/**"
  - "dist/**"
  - "package-lock.json"
  - ".git/**"
  - "**/*.svg"
  - "public/**"
  - "netlify.toml"
  - "_redirects"

words:
  - Actimize
  - Aerostructures
  - APICS
  - AUTOSAR
  - Baner
  - Bapat
  - bengaluru
  - Bengaluru
  - BESS
  - BFSI
  - Biopharmaceutical
  - Blinkit
  - CAMS
  - CCDM
  - CDISC
  - Chakan
  - CISO
  - CommerceTools
  - CPIM
  - crashworthiness
  - CSCP
  - Deshmukh
  - DPDP
  - ecommerce
  - eCRF
  - Elphinstone
  - ETAP
  - FATF
  - Fenergo
  - FinOps
  - frontends
  - FTWZ
  - Gachibowli
  - Glassmorphism
  - Guindy
  - gurugram
  - Gurugram
  - HANA
  - Hitec
  - homologation
  - interconnectivity
  - intermodal
  - ITES
  - Kharadi
  - knip
  - Koramangala
  - LGBTQIA
  - Madhapur
  - Magento
  - Malhotra
  - Manlog
  - MedDRA
  - Medidata
  - Mehta
  - milvus
  - Moller
  - multimodal
  - Multimodal
  - Noida
  - OFAC
  - omnichannel
  - Omnichannel
  - OpenTofu
  - Panchshil
  - pgvector
  - pincode
  - powertrains
  - Priya
  - PVsyst
  - Qdrant
  - Rahul
  - Rajeev
  - Renewables
  - RevPAR
  - rolldown
  - SDTM
  - SEBI
  - Senapati
  - Sethi
  - Sharma
  - specialities
  - Specialities
  - subline
  - Subline
  - TBML
  - tailwindcss
  - Vikram
  - webstores
  - Aadhaar
  - Amdocs
  - Anand
  - Arjun
  - Arun
  - Biopharma
  - cand
  - Karthik
  - Krishnan
  - Kulkarni
  - Markus
  - Meera
  - microgrid
  - Nalini
  - Nambiar
  - Rohan
  - Sundaram
  - Sunil
  - Sunita
  - Varma
  - Venkatraman
  - sourcers
